language: python

sudo: false

env:
    global:
        - LILYPOND_VERSION=2.19.44

python:
    - 3.5

before_install:
    - echo TRAVIS_PYTHON_VERSION $TRAVIS_PYTHON_VERSION
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-$LILYPOND_VERSION-1.linux-64.sh
    - sh lilypond-$LILYPOND_VERSION-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH
    - pip install -U pip

install:
    - pip install --allow-external consort --allow-unverified consort -e git://github.com/josiah-wolf-oberholtzer/consort.git#egg=consort
    - pip install -e .

script:
    - ajv doctest ./ersilia -x
    - py.test -rf -vv ./ersilia -x

notifications:
    email: false
